version: '3.8'

services:
  app:
    build: .
    container_name: consorcio-app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql://root:root@db:3306/consorcio
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: mysql:8
    container_name: consorcio-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: consorcio
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
