version: '3.8'

services:
  app:
    build: .
    container_name: consorcio-app
    ports:
      - "8000:80"
      - "8443:443"
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      consorcio:
        aliases:
          - consorcio

  db:
    image: mysql:8
    container_name: consorcio-db
    environment:
      - MYSQL_ROOT_PASSWORD=securerootpassword
      - MYSQL_DATABASE=db
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=secret
    ports:
      - "3305:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      consorcio:
        aliases:
          - db

volumes:
  db_data:

networks:
  consorcio:
    driver: bridge
